### ISSUE TITLE
Give Update

### ISSUE THREAD

**Issue by RkSoftWares** [SuperKali/MCStatusBot#3]
![Screenshot_2023-06-02-05-34-02-094_com android chrome-edit](https://github.com/SuperKali/MCStatusBot/assets/133474063/56ef9352-dfef-489a-81ba-72ad1d9fa1d3)

Make bot like this ScreenShot but for Mc Stats

**Comment by SuperKali** [comment]
@RkSoftWares sorry for the due reply, what do you mean like on the screenshot

**Comment by Princebhakta123** [comment]
@SuperKali but this is good to see and it's good for server owner
