### ISSUE TITLE
owner-id error

### ISSUE THREAD

**Issue by hieudieu393** [SuperKali/MCStatusBot#7]
i am filling it in but it is not working

**Comment by hieudieu393** [comment]
![IMG_20241016_161816](https://github.com/user-attachments/assets/a37b5aa6-c1d4-4f47-a2e3-4cc4990a69e6)

**Comment by SuperKali** [comment]
@hieudieu393 fixed on version https://github.com/SuperKali/MCStatusBot/releases/tag/v1.3
